version: '3.8'

services:
  vaultwarden:
    # Закомментировано для Portainer (развертывание заранее собранного образа),
    # если собираете через Dokploy или консоль, можно раскомментировать.
    # build: .

    image: custom-vaultwarden:latest
    container_name: vaultwarden
    restart: always

    environment:
      # ОСНОВНЫЕ
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:-false}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED:-true}
      - DOMAIN=https://ps.kolyachaba.top
      - SIGNUPS_VERIFY=${SIGNUPS_VERIFY:-false}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-}
      - INVITATIONS_ALLOWED=${INVITATIONS_ALLOWED:-true}
      - SHOW_PASSWORD_HINT=${SHOW_PASSWORD_HINT:-true}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - REQUIRE_DEVICE_EMAIL=${REQUIRE_DEVICE_EMAIL:-false}
      - SENDS_ALLOWED=${SENDS_ALLOWED:-true}
      - TRASH_AUTO_DELETE_DAYS=${TRASH_AUTO_DELETE_DAYS:-30}

      # Cloudflare Tunnel / Reverse Proxy настройки
      - IP_HEADER=CF-Connecting-IP

      # ДАННЫЕ
      - DATA_FOLDER=/data

    volumes:
      - vw-data:/data

    # ПРОБРОС ПОРТОВ ДЛЯ ТУННЕЛЯ НА ДРУГОЙ ВИРТУАЛЬНОЙ МАШИНЕ:
    # Portainer "выставит" этот контейнер на порт 8080 вашего сервера.
    # В настройках Cloudflare Tunnel (строка Service URL) укажите IP этого сервера и порт 8080 
    # (Например: http://192.168.1.100:8080)
    ports:
      - "8087:80"

volumes:
  vw-data:



